---
# This Playbook is used
# for testing containers on Testing Farm Fedora GPU

- hosts: all
  vars_files:
    - "group_vars/fedora"

  roles:
    - role: common_tools
    - role: services
    - role: clone_repos
  become: true
  become_user: root
