---
- name: Install basic tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - make
    - libseccomp-devel
    - postfix
    - acl

- name: Install Fedora packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - golang-github-cpuguy83-md2man
    - openssl
    - python-pip
    - s-nail
    - podman
    - podman-docker
    - pciutils
  when: releasever > 30

- name: Install CentOS Stream 8 packages
  package:
    name: "{{ item }}"
    state: latest
    validate_certs: no
    disable_gpg_check: true
  with_items:
    - https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/g/golang-github-cpuguy83-md2man-2.0.0-4.20210612gitaf8da76.el8.x86_64.rpm
    - mailx
    - podman
    - podman-docker
  when: releasever == 8

- name: Install CentOS Stream 9 packages
  package:
    name: "{{ item }}"
    state: latest
    validate_certs: no
    disable_gpg_check: true
  with_items:
    - https://kojihub.stream.centos.org/kojifiles/packages/golang-github-cpuguy83-md2man/2.0.0/16.gitaf8da76.el9/x86_64/golang-github-cpuguy83-md2man-2.0.0-16.gitaf8da76.el9.x86_64.rpm
    - s-nail
    - podman
    - podman-docker
  when: releasever == 9

- name: Install CentOS Stream 10 packages
  package:
    name: "{{ item }}"
    state: latest
    validate_certs: no
    disable_gpg_check: true
  with_items:
    - https://kojihub.stream.centos.org/kojifiles/vol/koji02/packages/golang-github-cpuguy83-md2man/2.0.3/3.el10/x86_64/golang-github-cpuguy83-md2man-2.0.3-3.el10.x86_64.rpm
    - s-nail
    - podman
    - podman-docker
  when: releasever == 10


- name: Create dir /etc/containers
  file:
    path: /etc/containers
    state: directory
    owner: root
    group: root
  when: releasever > 7

- name: ensure file /etc/containers/nodocker exists
  file:
    path: /etc/containers/nodocker
    state: touch
    mode: 0644
  when: releasever > 7
